image: "debian"

before_script:
    - apt update
    - apt install -y python3


validate_challenges:
    script:
        - src/validate.py challenges/* --verbose

build_test:
    script:
        - ctf-tool.py --address "ctf.cyberatuc.org" challenges/*

# install_test
# install_permissions_test
# service test
# docker test / 2.0
