image: "debian"

before_script:
    - scripts/install_required_packages.sh


validate_challenges:
#    stage: validate_challenges
    script:
        - src/validate.py challenges/* --verbose


build_basic:
#    stage: build_basic
    script:
        - ./ctf-tool.py --address "ctf.cyberatuc.org" challenges/*


build_install:
#    stage: build_install
    script:
        - apt install cron -y
        - ./ctf-tool.py --install-cron --address "ctf.cyberatuc.org" challenges/test-challenge-pack/
        - ls -lR /home/
        # TODO: assert correct permissions and that no extra files are added
        # TODO: note that v2 will use services which are easier to check

#stages:
#    - validate_challenges
#    - build_basic
#    - build_install

# TODO: v2 systemd service test
# TODO: v2 docker test
# TODO: v2 ansible package test

